//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW4.CachingData {
    
    
    public partial class _Default {
        
        /// <summary>
        /// ControlCurrentDateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HW4.CachingData.Controls.CurrentDateTime ControlCurrentDateTime;
    }
}
